### ISSUE TITLE
java.lang.ClassCastException

### ISSUE THREAD

**Issue by tianyin** [tianyin/conquid#2]
Parameter: "dfs.ha.log-roll.rpc.timeout"

java.lang.ClassCastException: soot.jimple.ClassConstant cannot be cast to soot.Local
	at generator.CheckerGenerator.generateChecker2(CheckerGenerator.java:409)
	at generator.CheckerGenerator.generateCheckers(CheckerGenerator.java:44)
	at main.PCheckPass.internalTransform(PCheckPass.java:43)
	at soot.SceneTransformer.transform(SceneTransformer.java:39)
	at soot.Transform.apply(Transform.java:90)
	at soot.ScenePack.internalApply(ScenePack.java:40)
	at soot.Pack.apply(Pack.java:116)
	at soot.PackManager.runWholeProgramPacks(PackManager.java:562)
	at soot.PackManager.runPacksNormally(PackManager.java:456)
	at soot.PackManager.runPacks(PackManager.java:391)
	at soot.Main.run(Main.java:244)
	at soot.Main.main(Main.java:152)
	at main.PCheck.hadoop(PCheck.java:150)
	at main.PCheck.main(PCheck.java:63)

**Comment by popacai** [comment]
INFO  - -------statement:i0 = virtualinvoke $r6.<org.apache.hadoop.conf.Configuration: int getInt(java.lang.String,int)>("dfs.ha.log-roll.rpc.timeout", 20000) returned
INFO  - -------statement:$l1 = staticinvoke <org.apache.hadoop.ipc.RPC: long getProtocolVersion(java.lang.Class)>(class "org/apache/hadoop/hdfs/protocolPB/NamenodeProtocolPB") 2invoke
INFO  - -------statement:$r8 = r0.<org.apache.hadoop.hdfs.server.namenode.ha.EditLogTailer: java.net.InetSocketAddress activeAddr> FLAG: 
INFO  - -------statement:$r7 = r0.<org.apache.hadoop.hdfs.server.namenode.ha.EditLogTailer: org.apache.hadoop.conf.Configuration conf> FLAG: 

"dfs.ha.log-roll.rpc.timeout"
